### ISSUE TITLE
Db

### ISSUE THREAD

**Issue by bitgorbovsky** [spanic/HolyErlang#2]
База данных в данном случае является процессом и все данные хранит в состоянии процесса, а не в файле.

**Comment by spanic** [comment]
Начиная с коммита 25e7b2f49d81906dca5b25c3132113a670e17ce0 **данные в прецессе передаются между функциями**, обращение к файлу происходит только в следующих этапах:
- **инициализация БД** (либо создаём новый файл для хранения данных, либо читаем уже имеющиеся пары ключ-значение);
- **сохранение изменений** в файл (через `database:commit/1`);
- **удаление БД** и файла (через `destroy/1`)
